targets:
  $default:
    builders:
      freezed:
        generate_for:
          include:
            - lib/**/*.dart
          exclude:
            - example/**
      riverpod_generator:
        generate_for:
          include:
            - lib/**/*.dart
          exclude:
            - example/**
