name: miroru_story_editor
description: "A new Flutter package project."
version: 0.0.1
homepage: https://miroru.com/

environment:
  sdk: ">=3.2.3 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  # entity
  freezed_annotation: ^2.4.1
  riverpod_annotation: ^3.0.0-dev.3

  matrix_gesture_detector_pro: ^1.0.0
  collection: ^1.18.0

  # icon
  ionicons: ^0.2.2
  font_awesome_flutter: ^10.6.0

  # font
  google_fonts: ^6.1.0

  # emoji
  animated_emoji: ^3.0.0

  # state management
  flutter_hooks: ^0.20.4
  hooks_riverpod: ^3.0.0-dev.3

  gap: any

  uuid: ^4.3.2

  blurhash_dart: ^1.2.1
  flutter_blurhash: ^0.8.2

  # animation
  align_positioned: ^4.0.0
  matrix4_transform: ^3.0.0
  image: ^4.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic_mono:
  custom_lint:
  riverpod_lint: ^3.0.0-dev.4

  build_runner:
  freezed:

  riverpod_generator: ^3.0.0-dev.11
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
# flutter:

# To add assets to your package, add an assets section, like this:
# assets:
#   - images/a_dot_burr.jpeg
#   - images/a_dot_ham.jpeg
#
# For details regarding assets in packages, see
# https://flutter.dev/assets-and-images/#from-packages
#
# An image asset can refer to one or more resolution-specific "variants", see
# https://flutter.dev/assets-and-images/#resolution-aware

# To add custom fonts to your package, add a fonts section here,
# in this "flutter" section. Each entry in this list should have a
# "family" key with the font family name, and a "fonts" key with a
# list giving the asset and other descriptors for the font. For
# example:
# fonts:
#   - family: Schyler
#     fonts:
#       - asset: fonts/Schyler-Regular.ttf
#       - asset: fonts/Schyler-Italic.ttf
#         style: italic
#   - family: Trajan Pro
#     fonts:
#       - asset: fonts/TrajanPro.ttf
#       - asset: fonts/TrajanPro_Bold.ttf
#         weight: 700
#
# For details regarding fonts in packages, see
# https://flutter.dev/custom-fonts/#from-packages
