name: miroru_story_editor
description: miroru story editor is built with an emphasis on ease of theme customization and a modern, extensible architecture. It adheres to Material Design guidelines using ThemeData for all theming, simplifying the process of modifying the app's look and feel.
version: 1.1.1
homepage: https://www.miroru.com/
repository: https://github.com/miroruX/miroru_story_editor

environment:
  sdk: ">=3.2.3 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  # localization
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1

  # dart
  uuid: ^4.3.2

  # image
  image: ^4.1.4
  blurhash_dart: ^1.2.1
  flutter_blurhash: ^0.8.2

  # entity
  freezed_annotation: ^2.4.1
  riverpod_annotation: ^2.3.3
  collection: ^1.18.0

  # sliver
  sliver_tools: ^0.2.12

  # icon
  ionicons: ^0.2.2
  font_awesome_flutter: ^10.6.0

  # font
  google_fonts: ^6.1.0

  # emoji
  animated_emoji: ^3.0.0
  unicode_emojis: ^0.3.0

  # state management
  flutter_hooks: ^0.20.4
  hooks_riverpod: ^2.4.9

  # animation
  align_positioned: ^4.0.0
  matrix4_transform: ^3.0.0
  matrix_gesture_detector_pro: ^1.0.0

  # paint
  perfect_freehand: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # lint
  pedantic_mono:
  custom_lint:
  riverpod_lint: ^2.3.7

  # build
  build_runner:
  freezed:

  riverpod_generator: ^2.3.9
  flutter_gen: ^5.4.0
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  generate: true
# To add assets to your package, add an assets section, like this:
# assets:
#   - images/a_dot_burr.jpeg
#   - images/a_dot_ham.jpeg
#
# For details regarding assets in packages, see
# https://flutter.dev/assets-and-images/#from-packages
#
# An image asset can refer to one or more resolution-specific "variants", see
# https://flutter.dev/assets-and-images/#resolution-aware

# To add custom fonts to your package, add a fonts section here,
# in this "flutter" section. Each entry in this list should have a
# "family" key with the font family name, and a "fonts" key with a
# list giving the asset and other descriptors for the font. For
# example:
# fonts:
#   - family: Schyler
#     fonts:
#       - asset: fonts/Schyler-Regular.ttf
#       - asset: fonts/Schyler-Italic.ttf
#         style: italic
#   - family: Trajan Pro
#     fonts:
#       - asset: fonts/TrajanPro.ttf
#       - asset: fonts/TrajanPro_Bold.ttf
#         weight: 700
#
# For details regarding fonts in packages, see
# https://flutter.dev/custom-fonts/#from-packages
